USE app;
CREATE TABLE IF NOT EXISTS todo (`id` INTEGER AUTO_INCREMENT PRIMARY KEY, `content` VARCHAR(255) NOT NULL, `isDone` BOOLEAN NOT NULL, `createdAt` DATE NOT NULL, `updatedAt` DATE NOT NULL, `creatorId` INTEGER NOT NULL, FOREIGN KEY (creatorId) REFERENCES user(id) ON DELETE CASCADE);
