CREATE DATABASE app;

USE app;

CREATE TABLE IF NOT EXISTS user (
	`id` INTEGER AUTO_INCREMENT PRIMARY KEY,
	`mail` VARCHAR(255) NOT NULL,
	`username` VARCHAR(100) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`refreshToken` VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS todo (
	`id` INTEGER AUTO_INCREMENT PRIMARY KEY,
	`content` VARCHAR(255) NOT NULL,
	`isDone` BOOLEAN NOT NULL,
	`createdAt`	DATE NOT NULL,
	`updatedAt`	DATE NOT NULL,
	`creatorId` INTEGER NOT NULL,
	FOREIGN KEY (creatorId) REFERENCES user(id) ON DELETE CASCADE
);
